In [27]:
import pandas as pd
df = pd.read_csv('houses_train.csv')

In [28]:
df

,Unnamed: 0,price,condition,district,max_floor,street,num_rooms,region,area,url,num_bathrooms,building_type,floor,ceiling_height
0,4598,100000.0,newly repaired,Arabkir,6,Kievyan St,3,Yerevan,96.0,http://www.myrealty.am/en/item/26229/3-senyaka...,1,stone,4,3.0
1,5940,52000.0,good,Arabkir,14,Mamikoniants St,3,Yerevan,78.0,http://www.myrealty.am/en/item/32897/3-senyaka...,1,panel,10,2.8
2,2302,52000.0,newly repaired,Qanaqer-Zeytun,9,M. Melikyan St,3,Yerevan,97.0,http://www.myrealty.am/en/item/1459/apartment-...,1,panel,1,2.8
3,5628,130000.0,good,Center,4,Spendiaryan St,3,Yerevan,80.0,http://www.myrealty.am/en/item/2099/3-senyakan...,1,stone,2,3.2
4,760,81600.0,zero condition,Center,9,Ler. Kamsar St,3,Yerevan,107.0,http://www.myrealty.am/en/item/22722/3-senyaka...,1,monolit,9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,3585,70000.0,newly repaired,Arabkir,5,Griboedov St,3,Yerevan,97.0,http://www.myrealty.am/en/item/36852/3-senyaka...,1,stone,4,2.8
4997,3291,77000.0,newly repaired,Arabkir,4,Orbeli Yeghbayrner St,3,Yerevan,71.0,http://www.myrealty.am/en/item/13933/Apartment...,1,stone,4,2.8
4998,5959,46000.0,zero condition,Center,5,Mashtots Ave,1,Yerevan,40.0,http://www.myrealty.am/en/item/31190/1-senyaka...,1,stone,2,3.0
4999,542,99000.0,newly repaired,Center,14,Argishti St,4,Yerevan,118.0,http://www.myrealty.am/en/item/25905/4-senyaka...,2,monolit,14,3.0
5000,4593,100000.0,newly repaired,Arabkir,5,Mamikoniants St,2,Yerevan,75.0,http://www.myrealty.am/en/item/28917/2-senyaka...,1,stone,3,3.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      5000 non-null   int64
 1   price           5000 non-null   float64
 2   condition       5000 non-null   object
 3   district        5000 non-null   object
 4   max_floor       5000 non-null   int64
 5   street          5000 non-null   object
 6   num_rooms       5000 non-null   int64
 7   region          5000 non-null   object
 8   area            5000 non-null   float64
 9   url             5000 non-null   object
 10  num_bathrooms   5000 non-null   int64
 11  building_type   5000 non-null   object
 12  floor           5000 non-null   int64
 13  ceiling_height  5000 non-null   float64
dtypes: float64(3), int64(5), object(6)
memory usage: 547.0+ KB

In [3]:
model = ...

In [ ]:
def final_predict(final_test_df):
    1. preprocessing of final_test_df (scaling, one hot encoding ...)
    2. make sure that columns and their order in train and test are the same
    3. return predictions

In [ ]:
df = pd.read_csv('houses_test.csv')
final_predict(df)